server {
    listen 80;
    location ~ ^/data/api/graph/([^/]+)/players$ {
        limit_req zone=heavy_rate burst=2 nodelay;
        limit_req_status 429;

        proxy_pass http://backend:3000/graph/$1/players$is_args$args;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location ~ ^/data/api/graph/([^/]+)/event_count$ {
        limit_req zone=semi_heavy_rate burst=6 nodelay;
        limit_req_status 429;

        proxy_pass http://backend:3000/graph/$1/event_count$is_args$args;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location ~ ^/data/api/graph/([^/]+)/unique_players$ {
        limit_req zone=semi_heavy_rate burst=6 nodelay;
        limit_req_status 429;

        proxy_pass http://backend:3000/graph/$1/unique_players$is_args$args;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /data/api/ {
        proxy_pass http://backend:3000/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /thumbnails/ {
        root /var/www;
        try_files $uri $uri/ @backend;
    }

    location @backend {
        proxy_pass http://backend:3000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location ~ ^/tiles/(?<layer>[^/]+)/(?<z>\d+)/(?<x>\d+)/(?<y>\d+)\.png$ {
        set $query "layer=$layer&tilematrixset=EPSG:3857&Service=WMTS&Request=GetTile&Format=image/png&TileMatrix=$z&TileCol=$x&TileRow=$y";

        rewrite ^ /qgis-server?$query break;
        fastcgi_cache qgis_cache;
        fastcgi_cache_key "$uri?$query";

        fastcgi_cache_valid 200 365d;
        fastcgi_cache_valid any 5m;
        fastcgi_cache_lock on;

        fastcgi_ignore_headers Cache-Control;
        add_header X-Cache-Status $upstream_cache_status;

        include fastcgi_params;
        fastcgi_param SCRIPT_NAME /qgis-server;
        fastcgi_pass qgis-server:9993;
    }

    location /qgis-server {
      proxy_buffers 16 16k;
      proxy_buffer_size 16k;
      gzip off;
      include fastcgi_params;
      fastcgi_pass qgis-server:9993;
    }

    location ~* ^/models/maps/(.+\.(gltf|glb|png|jpg|jpeg))$ {
        alias /var/www/frontend/public/$1;
        expires 7d;
        add_header Cache-Control "public, max-age=604800, immutable";
        access_log off;
    }

    location ~* ^/models/characters/(.+\.(gltf|glb|png|jpg|jpeg))$ {
        alias /var/www/characters/$1;
        expires 7d;
        add_header Cache-Control "public, max-age=604800, immutable";
        access_log off;
    }

    location / {
        proxy_pass http://frontend:5173/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}