FROM oven/bun:alpine AS builder

WORKDIR /app

COPY package*.json bun.lock ./

RUN bun ci

ARG BUILD_ENV=development
ARG DISCORD_CLIENT_ID=""
ARG NEXT_PUBLIC_DISCORD_REDIRECT_URI=""
ARG DISCORD_CLIENT_SECRET=""
ARG NEXT_PUBLIC_DOMAIN=""
ARG NEXTAUTH_SECRET=""
ARG STEAM_SECRET=""
ARG NEXTAUTH_URL=""
ARG FRONTEND_URL=""
ARG NEXT_PUBLIC_POSTHOG_KEY=""
ARG NEXT_PUBLIC_POSTHOG_HOST=""
ARG NEXT_PUBLIC_ADSENSE_CLIENT_ID=""
ARG NEXT_PUBLIC_ADSENSE_AD_SLOT=""
ARG NEXT_PUBLIC_AD_SHOW=""
# .git is dockerignored, so next.config.ts cannot resolve HEAD in here.
ARG BUILD_COMMIT=""

RUN printf "Building in environment: $BUILD_ENV\n"

COPY . .

RUN cat <<EOF > .env.development
DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
NEXTAUTH_URL=${NEXTAUTH_URL}
DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
NEXT_PUBLIC_DISCORD_REDIRECT_URI=${NEXT_PUBLIC_DISCORD_REDIRECT_URI}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
STEAM_SECRET=${STEAM_SECRET}
NEXT_PUBLIC_DOMAIN=${NEXT_PUBLIC_DOMAIN}
FRONTEND_URL=${FRONTEND_URL}
NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}
NEXT_PUBLIC_ADSENSE_CLIENT_ID=${NEXT_PUBLIC_ADSENSE_CLIENT_ID}
NEXT_PUBLIC_ADSENSE_AD_SLOT=${NEXT_PUBLIC_ADSENSE_AD_SLOT}
NEXT_PUBLIC_AD_SHOW=${NEXT_PUBLIC_AD_SHOW}
BUILD_COMMIT=${BUILD_COMMIT}
EOF

EXPOSE 5173

RUN apk add --no-cache curl

CMD ["bun", "run", "dev", "--", "-p", "5173"]