on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write

    name: Reset development on merge
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - run: |
          git checkout development
          git reset --hard origin/main
          git push --force origin development
